name: Payment CICD
run-name: payment CICD
on:
  push:
    branches:
    - main
      
jobs:
  ci:
    uses: azawsdevops/github-reusable-modules/.github/workflows/ci-main-branch.yaml@main
    with:
      component: payment
      appType: nodejs
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
  deploy:
    uses: azawsdevops/github-reusable-modules/.github/workflows/deploy.yaml@main
    with:
      component: payment
      