name: Payment CICD
run-name: payment CICD
on:
  push:
    branches:
    - main
jobs:
  ci:
    uses: azawsdevops/github-reusable-modules/.github/workflows/ci.yaml@main
    with:
      component: payment
      appType: nodejs
  deploy:
    uses: azawsdevops/github-reusable-modules/.github/workflows/deploy.yaml@main
    with:
      component: payment
      